services:
  clothing-model:
    image: ai-lesson-clothing-model:xception-v4-001
  gateway:
    image: ai-lesson-gateway:001
    environment:
      - TF_SERVING_HOST=clothing-model:8500
    ports:
      - "9696:9696"