apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 647677696628.dkr.ecr.ap-southeast-1.amazonaws.com/ai-lesson-kuber-images:ai-lesson-gateway-001
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 9696
          env:
            - name: TF_SERVING_HOST
              value: tf-serving-clothing-model.default.svc.cluster.local:8500
